### ISSUE TITLE
Funds in unclaimed conditionalTransfer remain locked

### ISSUE THREAD

**Issue by erkarl** [connext/indra#1173]
## Current Behavior
After the locktime has expired the funds remain locked in the app.

## Expected Behavior
The client should detect when the conditional transfer has not been claimed within the specified locktime and automatically call `uninstallApp.(appInstanceId)` to release the funds or dispute on-chain.

**Comment by kilrau** [comment]
> or dispute on-chain
if the node decides **not** to cooperate, meaning `uninstallApp.(appInstanceId)` hits a timeout

**Comment by ArjunBhuptani** [comment]
Part of this will be solved here: https://github.com/connext/indra/issues/1101

And then we'll have to think through how the client/node clean up transfers on a schedule

**Comment by kilrau** [comment]
Agreed, https://github.com/connext/rest-api-client/issues/37 was largely the same. Just transferring this small requirement here: client constantly retries claiming the htlc up to the dispute timeout. Then, as @erkarl described above, automatically calls `uninstallApp.(appInstanceId)` to release the funds or dispute on-chain if this doesn't work within a certain time period (we discussed one day). It should go on-chain well before htlc timeout.

**Comment by kilrau** [comment]
> The client should detect when the conditional transfer has not been claimed within the specified locktime and automatically call uninstallApp.(appInstanceId) to release the funds or dispute on-chain.

As per recent discussion, we agreed that the client does **not** need to schedule htlc cleanups as long as
a) it exposes a simple call that an external service ([like xud](https://github.com/ExchangeUnion/xud)) could hit to cancel and clean-up unclaimed htlcs (please let us know which one since you mentioned two on the call @ArjunBhuptani @LayneHaber )
b) the node schedules automated uninstalling htlcs after expiry, retries if it fails
c) the client automatically triggers uninstalling expired htlcs on startup since b) can fail because client was offline
